name: build-onboard
on:
  push:
    branches:
      - master
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  compile:
    name: Run Juliac
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    steps:
        - uses: actions/checkout@v4
        - name: Checkout Zenoh repo
          uses: actions/checkout@v4
          with:
            repository: benchung/Zenoh.jl
            path: dev/zenoh
        - name: Checkout CDRSerialization repo
          uses: actions/checkout@v4
          with:
            repository: benchung/CDRSerialization.jl
            path: dev/cdr
        - name: Checkout PX4 messages repo
          uses: actions/checkout@v4
          with:
            repository: benchung/PX4.jl
            path: dev/px4messages
        - name: Checkout custom CClosure repo
          uses: actions/checkout@v4
          with:
            repository: BenChung/CClosure.jl
            ref: generated-closure
            path: dev/cclousre
        - uses: julia-actions/install-juliaup@v2
          with:
            channel: 'pr58655'
        - uses: julia-actions/cache@v2
        - run: julia -e 'import Pkg; Pkg.activate("juliac"); Pkg.develop([Pkg.PackageSpec(path="."), Pkg.PackageSpec(path="dev/zenoh"), Pkg.PackageSpec(path="dev/cdr"), Pkg.PackageSpec(path="dev/px4messages"), Pkg.PackageSpec(path="dev/cclousre")])'
        - run: cd juliac && julia --project $(julia -e "println(Sys.BINDIR)")/../share/julia/juliac/juliac.jl --output-exe qfc --experimental --trim=unsafe-warn ./onboard.jl
          env:
            JULIA_CPU_TARGET: cortex-a72
        - uses: actions/upload-artifact@v4
          with:
            name: qfc
            path: qfc